[package]
name = "rdb2rdf"
version = "0.1.0"
authors = [""]

[dependencies]
serde = "1.0.55"
serde_derive = "1.0.55"
serde_json = "1.0.17"
yaml-rust = "0.4.0"
xml-rs = "0.7.0"
csv = "0.15.0"
prettytable-rs = "0.7.0"
algorithm = { path = "../algorithm", version = "0.1.0" }