logging:
    __workdir__: logs
    version: 1
    formatters:
        full:
            format: '%(levelname)s:%(name)s:%(module)s:%(funcName)s:%(lineno)03d:%(asctime)s - %(message)s'
        brief:
            format: '%(levelname)s:%(name)s:%(module)s:%(lineno)03d - %(message)s'
        time_minimum:
            format: '%(levelname)s:%(asctime)s:%(name)s:  %(message)s'
        minimum:
            format: '%(levelname)s:%(name)s:  %(message)s'
        naked:
            format: '%(message)s'
    handlers:
        $rolling_console$:
            id: [console, minimum_console, time_minimum_console, naked_console, full_console]
            class: logging.StreamHandler
            formatter: [brief, minimum, time_minimum, naked, full]
            level: TRACE
            stream: ext://sys.stdout
        $rolling_file$:
            id: [time_minimum_file, time_minimum_persistent_file]
            class: pyutils.logging_utils.DynamicFileHandler
            basedir: "@#."
            formatter: time_minimum
            level: TRACE
            mode: w
            folder_base: [false, true]
    loggers:
        elasticsearch:
            level: ERROR
        default:
            id: default
            level: DEBUG
            propagate: false
            handlers: [full_console]
        app:
            id: app
            level: DEBUG
            propagate: false
            handlers: [time_minimum_console, time_minimum_file]
        app.persistent:
            id: app.persistent
            level: DEBUG
            propagate: false
            handlers: [time_minimum_console, time_minimum_persistent_file]
        app.assembling.search_discovery:
            id: app.assembling.search_discovery
            level: DEBUG
            propagate: false
            handlers: [time_minimum_console]
        app.semantic_labeling.stype_db:
            id: app.semantic_labeling.stype_db
            level: DEBUG
            propagate: false
            handlers: [time_minimum_console]
        app.weak_models.stype_assistant:
            id: app.weak_models.stype_assistant
            level: DEBUG
            propagate: false
            handlers: [time_minimum_console]
    root:
        level: INFO
        handlers: [console]
