[package]
name = "algorithm"
version = "0.1.0"
authors = ["rook"]

[dependencies]
serde = "1.0.*"
serde_derive = "1.0.*"
serde_json = "1.0.17"
libc = "0.2.0"
rand = "0.5.*"
fnv = "1.0.6"
ndarray = { version = "0.11.*", features = ["serde-1"] }
regex = "1"