- name: install common packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
  become: yes
  vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - gnupg2
      - python-pip
- name: setup docker official GPG key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: setup docker repository
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    state: present
- name: install docker ce
  become: yes
  apt:
    name: docker-ce
    update_cache: yes
- name: setup docker-compose (pip)
  pip:
    name: docker-compose
- name: install docker-compose (later)
  become: yes
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.21.2/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: g=rx,o=rx
- name: create docker group
  group:
    name: docker
    state: present
- name: add user to docker group
  become: yes
  user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: yes